on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: standingserviceacr.azurecr.io
        username: ${{ secrets.acr_standingserviceacr_username }}
        password: ${{ secrets.acr_standingserviceacr_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/" -f  "Dockerfile" -t standingserviceacr.azurecr.io/sanrocksstandingserviceakscluster:${{ github.sha }} --label dockerfile-path=Dockerfile
        docker push standingserviceacr.azurecr.io/sanrocksstandingserviceakscluster:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_sanrocksstandingserviceakscluster_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep sanrocks-standing-service-aks-clustera49b | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace sanrocks-standing-service-aks-clustera49b`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: sanrocks-standing-service-aks-clustera49b
        container-registry-url: standingserviceacr.azurecr.io
        container-registry-username: ${{ secrets.acr_standingserviceacr_username }}
        container-registry-password: ${{ secrets.acr_standingserviceacr_password }}
        secret-name: sanrocksstandockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: sanrocks-standing-service-aks-clustera49b
        manifests: |
          manifests/deployment.yml
          manifests/service.yml
        images: |
          standingserviceacr.azurecr.io/sanrocksstandingserviceakscluster:${{ github.sha }}
        imagepullsecrets: |
          sanrocksstandockerauth
